AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: The autologin AWS stack
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  register:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RegisterLambda
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: autologinRegisterLambda/function/.
      Description: Call the Register Lambda
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /
            Method: GET  
  notifier:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NotifierLambda
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: autologinNotifierLambda/function/.
      Description: Autologin Notifier Lambda
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: autologin-notifier-lambda-lib
      Description: Dependencies for the autologin register lambda.
      ContentUri: autologinNotifierLambda/lib/.
      CompatibleRuntimes:
        - nodejs14.x
